"""add_profile_fields_to_user

Revision ID: 1034c2f168b6
Revises: f28765d7effb
Create Date: 2026-01-14 02:54:09.062596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1034c2f168b6'
down_revision: Union[str, None] = 'f28765d7effb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###
