"""refactor_asset_post_relationship

Revision ID: 14582f09c4e8
Revises: ca75fb354d93
Create Date: 2025-12-26 01:17:24.203883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14582f09c4e8'
down_revision: Union[str, None] = 'ca75fb354d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_assets',
                    sa.Column('post_id', sa.String(length=26), nullable=False),
                    sa.Column('asset_id', sa.String(length=26), nullable=False),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_id', 'asset_id')
                    )
    # Drop indexes if they exist (some DBs may have different naming)
    try:
        op.drop_index('ix_assets_owner_type', table_name='assets')
    except Exception:
        pass
    try:
        op.drop_index('ix_assets_post_id', table_name='assets')
    except Exception:
        pass

    # Drop FK from assets.post_id -> posts.id. The constraint name may vary
    # across DBs (autogenerated vs explicit). Inspect and drop the matching FK.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    for fk in inspector.get_foreign_keys('assets'):
        constrained = fk.get('constrained_columns') or fk.get('constrained_columns')
        if fk.get('referred_table') == 'posts' and constrained == ['post_id']:
            fk_name = fk.get('name')
            if fk_name:
                try:
                    op.drop_constraint(fk_name, 'assets', type_='foreignkey')
                except Exception:
                    # if drop fails, re-raise to surface error
                    raise
            break

    # Remove columns if present
    try:
        op.drop_column('assets', 'owner_type')
    except Exception:
        pass
    try:
        op.drop_column('assets', 'post_id')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('post_id', sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('owner_type', sa.VARCHAR(length=32), nullable=False, server_default='user'))
    op.alter_column('assets', 'owner_type', server_default=None)
    op.create_foreign_key('assets_post_id_fkey', 'assets', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_assets_post_id', 'assets', ['post_id'], unique=False)
    op.create_index('ix_assets_owner_type', 'assets', ['owner_type'], unique=False)
    op.drop_table('post_assets')
    # ### end Alembic commands ###
