"""refactor_asset_post_relationship

Revision ID: 14582f09c4e8
Revises: ca75fb354d93
Create Date: 2025-12-26 01:17:24.203883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14582f09c4e8'
down_revision: Union[str, None] = 'ca75fb354d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_assets',
                    sa.Column('post_id', sa.String(length=26), nullable=False),
                    sa.Column('asset_id', sa.String(length=26), nullable=False),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_id', 'asset_id')
                    )
    op.drop_index('ix_assets_owner_type', table_name='assets')
    op.drop_index('ix_assets_post_id', table_name='assets')
    op.drop_constraint('assets_post_id_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'owner_type')
    op.drop_column('assets', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('post_id', sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('owner_type', sa.VARCHAR(length=32), nullable=False, server_default='user'))
    op.alter_column('assets', 'owner_type', server_default=None)
    op.create_foreign_key('assets_post_id_fkey', 'assets', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_assets_post_id', 'assets', ['post_id'], unique=False)
    op.create_index('ix_assets_owner_type', 'assets', ['owner_type'], unique=False)
    op.drop_table('post_assets')
    # ### end Alembic commands ###
