"""Add product_id to post_assets

Revision ID: 16ae3c917486
Revises: 1034c2f168b6
Create Date: 2026-01-27 02:42:50.991353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ae3c917486'
down_revision: Union[str, None] = '1034c2f168b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_assets', sa.Column('product_id', sa.String(length=26), nullable=True))
    op.create_foreign_key('fk_post_assets_product_id', 'post_assets', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_users_avatar_asset_id', 'users', ['avatar_asset_id'])
    op.create_foreign_key('fk_users_avatar_asset_id', 'users', 'assets', ['avatar_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_avatar_asset_id', 'users', type_='foreignkey')
    op.drop_constraint('uq_users_avatar_asset_id', 'users')
    op.drop_constraint('fk_post_assets_product_id', 'post_assets', type_='foreignkey')
    op.drop_column('post_assets', 'product_id')
    # ### end Alembic commands ###
