"""add payment_type and purchase_status enums

Revision ID: 2fd7fb9f1095
Revises: ad8af600fa4b
Create Date: 2026-01-15 02:16:24.830574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd7fb9f1095'
down_revision: Union[str, None] = 'ad8af600fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types first
    paymenttype_enum = sa.Enum('CREDIT_CARD', 'CONVENIENCE_STORE', 'BANK_TRANSFER', 'DIGITAL_WALLET', name='paymenttype')
    purchasestatus_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchasestatus')
    
    paymenttype_enum.create(op.get_bind(), checkfirst=True)
    purchasestatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Convert VARCHAR to Enum with USING clause
    op.execute('ALTER TABLE payment_methods ALTER COLUMN payment_type TYPE paymenttype USING (payment_type::paymenttype)')
    op.execute('ALTER TABLE purchases ALTER COLUMN status TYPE purchasestatus USING (status::purchasestatus)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchasestatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_methods', 'payment_type',
               existing_type=sa.Enum('CREDIT_CARD', 'CONVENIENCE_STORE', 'BANK_TRANSFER', 'DIGITAL_WALLET', name='paymenttype'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    
    # Drop Enum types
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchasestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum('CREDIT_CARD', 'CONVENIENCE_STORE', 'BANK_TRANSFER', 'DIGITAL_WALLET', name='paymenttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
