"""add payment_type and purchase_status enums

Revision ID: 2fd7fb9f1095
Revises: ad8af600fa4b
Create Date: 2026-01-15 02:16:24.830574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd7fb9f1095'
down_revision: Union[str, None] = 'ad8af600fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_methods', 'payment_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('CREDIT_CARD', 'CONVENIENCE_STORE', 'BANK_TRANSFER', 'DIGITAL_WALLET', name='paymenttype'),
               existing_nullable=False)
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchasestatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchasestatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_methods', 'payment_type',
               existing_type=sa.Enum('CREDIT_CARD', 'CONVENIENCE_STORE', 'BANK_TRANSFER', 'DIGITAL_WALLET', name='paymenttype'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
