"""drop_id_ulid

Revision ID: 32b17fbe34d4
Revises: 91432243e31e
Create Date: 2025-11-07 05:11:00.375364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b17fbe34d4'
down_revision: Union[str, None] = '91432243e31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)
    op.drop_index('ix_users_id_ulid', table_name='users')
    op.drop_column('users', 'id_ulid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_ulid', sa.VARCHAR(length=26), autoincrement=False, nullable=False))
    op.create_index('ix_users_id_ulid', 'users', ['id_ulid'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=26),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
