"""Change token_hash to refresh_token VARCHAR(1024)

Revision ID: 44eef51b39f3
Revises: 8035f2c5d092
Create Date: 2025-11-18 06:51:52.509995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44eef51b39f3'
down_revision: Union[str, None] = '8035f2c5d092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.String(length=1024), nullable=False))
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=True)
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###
