"""add_post_assets_table

Revision ID: 50b542603e05
Revises: 5bd8e656c8da
Create Date: 2025-12-16 01:22:55.491287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b542603e05'
down_revision: Union[str, None] = '5bd8e656c8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_assets',
    sa.Column('post_id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_assets')
    # ### end Alembic commands ###
