"""add_is_purchase_history_public_to_users

Revision ID: 630a62d47916
Revises: a099118e8ba4
Create Date: 2026-02-28 14:34:43.759681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630a62d47916'
down_revision: Union[str, None] = 'a099118e8ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_purchase_history_public', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_purchase_history_public')
    # ### end Alembic commands ###
