"""alter_users

Revision ID: 7fe37befb737
Revises: 9ead5d0ce61c
Create Date: 2025-11-06 03:35:37.212591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe37befb737'
down_revision: Union[str, None] = '9ead5d0ce61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('confirmation_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('confirmation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_confirmation_token'), 'users', ['confirmation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_confirmation_token'), table_name='users')
    op.drop_column('users', 'confirmation_expires_at')
    op.drop_column('users', 'confirmation_sent_at')
    op.drop_column('users', 'confirmation_token')
    op.drop_column('users', 'is_confirmed')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
