"""Use Enum(PostStatus) for posts.status

Revision ID: 97e23920c6d0
Revises: 14582f09c4e8
Create Date: 2026-01-03 10:01:48.980866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e23920c6d0'
down_revision: Union[str, None] = '14582f09c4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type before altering the column (Postgres requires the type to exist).
    post_status_enum = sa.Enum('draft', 'public', 'archived', name='post_status')
    post_status_enum.create(op.get_bind(), checkfirst=True)

    # Use explicit USING cast to convert existing string values to the new ENUM type.
    op.execute("ALTER TABLE posts ALTER COLUMN status TYPE post_status USING status::post_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter column back to VARCHAR then drop the ENUM type
    # Convert back to VARCHAR using an explicit cast, then drop the enum type.
    op.execute("ALTER TABLE posts ALTER COLUMN status TYPE VARCHAR(16) USING status::text")

    post_status_enum = sa.Enum('draft', 'public', 'archived', name='post_status')
    post_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
