"""add_is_deleted_to_comments

Revision ID: a099118e8ba4
Revises: e0d603f9422a
Create Date: 2026-02-11 21:33:43.742477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a099118e8ba4'
down_revision: Union[str, None] = 'e0d603f9422a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
