"""refactor_asset_to_one_to_many

Revision ID: ca75fb354d93
Revises: 50b542603e05
Create Date: 2025-12-16 01:47:14.707170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca75fb354d93'
down_revision: Union[str, None] = '50b542603e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_assets')
    op.add_column('assets', sa.Column('post_id', sa.String(length=26), nullable=True))
    op.create_index(op.f('ix_assets_post_id'), 'assets', ['post_id'], unique=False)
    op.create_foreign_key('fk_assets_post_id_posts', 'assets', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the FK that points assets.post_id -> posts.id. The exact constraint name
    # may differ depending on whether the FK was created with an explicit name
    # or an autogenerated one. Inspect and drop the matching constraint if found.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    fk_dropped = False
    for fk in inspector.get_foreign_keys('assets'):
        # constrained_columns may be a list like ['post_id']
        constrained = fk.get('constrained_columns') or fk.get('constrained_columns')
        if fk.get('referred_table') == 'posts' and constrained == ['post_id']:
            fk_name = fk.get('name')
            if fk_name:
                op.drop_constraint(fk_name, 'assets', type_='foreignkey')
                fk_dropped = True
                break

    if not fk_dropped:
        # Fallback: attempt to drop the expected constraint name, ignore if missing.
        try:
            op.drop_constraint('fk_assets_post_id_posts', 'assets', type_='foreignkey')
        except Exception:
            # If still failing, re-raise to surface unexpected errors
            raise

    op.drop_index(op.f('ix_assets_post_id'), table_name='assets')
    op.drop_column('assets', 'post_id')
    op.create_table('post_assets',
    sa.Column('post_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='post_assets_asset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_assets_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'asset_id', name='post_assets_pkey')
    )
    # ### end Alembic commands ###
