"""add_indexes_to_posts_for_public_list

Revision ID: f28765d7effb
Revises: 031149f18cd4
Create Date: 2026-01-05 02:00:50.153291

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f28765d7effb'
down_revision: Union[str, None] = '031149f18cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # created_at インデックス（タイムライン取得の高速化）
    op.create_index(
        op.f('ix_posts_created_at'),
        'posts',
        ['created_at'],
        unique=False
    )

    # status + created_at 複合インデックス（公開投稿フィルタの高速化）
    op.create_index(
        'ix_posts_status_created_at',
        'posts',
        ['status', 'created_at'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    # ### end Alembic commands ###
